// Code generated by MockGen. DO NOT EDIT.
// Source: ./../client/services/operation/operation.go

// Package serviceMocks is a generated GoMock package.
package serviceMocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	types "github.com/lidofinance/dc4bc/client/types"
)

// MockOperationService is a mock of OperationService interface.
type MockOperationService struct {
	ctrl     *gomock.Controller
	recorder *MockOperationServiceMockRecorder
}

// MockOperationServiceMockRecorder is the mock recorder for MockOperationService.
type MockOperationServiceMockRecorder struct {
	mock *MockOperationService
}

// NewMockOperationService creates a new mock instance.
func NewMockOperationService(ctrl *gomock.Controller) *MockOperationService {
	mock := &MockOperationService{ctrl: ctrl}
	mock.recorder = &MockOperationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOperationService) EXPECT() *MockOperationServiceMockRecorder {
	return m.recorder
}

// DeleteOperation mocks base method.
func (m *MockOperationService) DeleteOperation(operation *types.Operation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOperation", operation)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOperation indicates an expected call of DeleteOperation.
func (mr *MockOperationServiceMockRecorder) DeleteOperation(operation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOperation", reflect.TypeOf((*MockOperationService)(nil).DeleteOperation), operation)
}

// GetOperationByID mocks base method.
func (m *MockOperationService) GetOperationByID(operationID string) (*types.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOperationByID", operationID)
	ret0, _ := ret[0].(*types.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOperationByID indicates an expected call of GetOperationByID.
func (mr *MockOperationServiceMockRecorder) GetOperationByID(operationID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOperationByID", reflect.TypeOf((*MockOperationService)(nil).GetOperationByID), operationID)
}

// GetOperations mocks base method.
func (m *MockOperationService) GetOperations() (map[string]*types.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOperations")
	ret0, _ := ret[0].(map[string]*types.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOperations indicates an expected call of GetOperations.
func (mr *MockOperationServiceMockRecorder) GetOperations() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOperations", reflect.TypeOf((*MockOperationService)(nil).GetOperations))
}

// PutOperation mocks base method.
func (m *MockOperationService) PutOperation(operation *types.Operation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutOperation", operation)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutOperation indicates an expected call of PutOperation.
func (mr *MockOperationServiceMockRecorder) PutOperation(operation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutOperation", reflect.TypeOf((*MockOperationService)(nil).PutOperation), operation)
}
