name: Build release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          [linux/amd64, linux/arm64, linux/386, darwin/amd64, darwin/arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and export
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: platform=${{ matrix.platform }}
          outputs: type=local,dest=./build

      - name: Parse platform
        id: parse
        run: |
          echo ${{ matrix.platform }} | {
            IFS='/' read -r OS ARCH
            echo "platform=$OS-$ARCH" >> $GITHUB_OUTPUT
          }

      - name: Tar files
        run: tar -cvf build-${{ steps.parse.outputs.platform }}.tar build/*

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-${{ steps.parse.outputs.platform }}
          path: build-${{ steps.parse.outputs.platform }}.tar
