name: Go

on: [push]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.19.4
      uses: actions/setup-go@v2
      with:
        go-version: 1.19.4
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: make build-linux

    - name: Test
      run: make test
